---
- hosts: all
  user: root
  gather_facts: no
  pre_tasks:
    - name: install python
      raw: sudo apt-get -y install python-minimal

    - action: setup

  roles:
    - role: bootstrap/0.0.1
      authorized_key_paths:
        - ../../public_keys/*.pub

    - role: user/0.0.1
      username: admin
      sudoer: True
      authorized_key_paths:
        - ../../public_keys/*.pub

    - role: install-build-essential/0.0.1

    - role: install_elixir/0.0.1

    - role: install_nodejs/0.0.1

    - role: user/0.0.1
      username: builder
      authorized_key_paths:
        - ../../public_keys/*.pub
        - ./circle_ci.pub

    # This must be the last one role to log info about successfully provisioned machine.
    - role: provision_log/0.0.1
